### ISSUE TITLE
The $gain/loss string in the header area shows $USD, not £GBP

### ISSUE THREAD

**Issue by mprussell** [vinniejames/coinfox#10]
The `$gain/loss` value in the header (below, left relative to the `Total portfolio $value` figure) shows a $ dollar sign, though the currency selected for my portfolio items is £GBP. 

The calculated value in `Total portfolio $value` is correct, only the currency symbol is incorrect. (And the symbol is correct in the transaction line, top right.)

---
#### Footnote: 
Coinfox is excellent. Thanks. Clean and simple, unlike all of the others. You should credit yourself in there. I had to search to find your Github repo.

**Comment by vinniejames** [comment]
Thanks for the compliments! Hope youre enjoying it

Fixed the currency symbol https://github.com/vinniejames/coinfox/pull/12/commits/e543259d8de18fa11302572533d7f0c6201e318d

**Comment by vinniejames** [comment]
PS, not sure where you are using the app, but ive setup a new domain name for it here: [coinfox.co](http://coinfox.co)

Please update your bookmarks! Also if you "Add to Home Screen" on iOS or Android it works full screen just like a mobile app

@mprussell
