### ISSUE TITLE
May we have CHF as well?

### ISSUE THREAD

**Issue by philippeowagner** [vinniejames/coinfox#14]
This would be great. Thanks in advance.

**Comment by philippeowagner** [comment]
Calling [BTC-CHF](https://api.cryptonator.com/api/ticker/btc-chf) returns `{"success":false,"error":"Pair not found"}`.

**Comment by philippeowagner** [comment]
https://min-api.cryptocompare.com/data/histoday?aggregate=1&e=CCCAGG&extraParams=CryptoCompare&fsym=ETH&limit=365&tryConversion=false&tsym=CHF -> `{"Response":"Error","Message":"CCCAGG market does not exist for this coin pair","Type":1,"Aggregated":false,"Data":[]}`

**Comment by vinniejames** [comment]
I'll take a look at your PR, that should work. Can you quickly confirm you have read the license ? https://github.com/vinniejames/coinfox/blob/master/LICENSE.md

**Comment by philippeowagner** [comment]
Nice!
