### ISSUE TITLE
What about to load the "safe file" from an URL?

### ISSUE THREAD

**Issue by philippeowagner** [vinniejames/coinfox#15]
This would enable to *sync over multiple devices* and let a *backend write the file and do the avg-cost per coin calculation* that his consumed by coinfox.co.  

Great app BTW! Was looking for something like this for weeks now!

**Comment by vinniejames** [comment]
I was thinking about doing just this. The hope was to avoid exposing any personal information. So I prefer it to storing any user data

But, I suppose a password could be required to en/decrypt the URL string

Thanks man!

**Comment by philippeowagner** [comment]
An elaborate solution is what Keepass2Android provides... 

![](https://lh3.googleusercontent.com/9lgSzyeqbkPAifOMK7SQphicWjKjWTn9Yar5j1uzGai7VzGlN9T3-pej_wqpwrxT0A=h900-rw)

Maybe another option (FTP, Dropbox, ..) would do the trick as well without exposing the data. In addition read _and write_ could be possible.

**Comment by philippeowagner** [comment]
I'm not native with this _JavaScripty-Reacty-thing_, but I made a [prototype]( https://github.com/philippeowagner/coinfox/commit/51bf2bb0ad6bee6749d942bf4c9b625a15d73474). The data is random and hard-coded in the prototype.
In the future, the file could be encrypted and decrypted using the [Stanford Javascript Crypto Library](http://bitwiseshiftleft.github.io/sjcl/).
