### ISSUE TITLE
Kraken GBP cull means no GBP data

### ISSUE THREAD

**Issue by mprussell** [vinniejames/coinfox#18]
Kraken killed their GBP pairs. Their GBP ticker data is now defunct too. Coinfox uses the cryptonator.com API for price data. Cryptonator's GBP data comes from Kraken only. So, Coinfox now displays £0.00 for GBP. (See screenshot.)

There are other GBP data sources, and perhaps cryptonator.com doesn't realise the Kraken GBP data has stopped. Perhaps they could be told?

![image](https://user-images.githubusercontent.com/349371/29662375-054c8476-88bf-11e7-8e8c-e20218b0830c.png)

**Comment by mprussell** [comment]
Fixed. Cryptonator switched to CEX.io

https://www.cryptonator.com/exchange/

**Comment by vinniejames** [comment]
Thanks for following up
