### ISSUE TITLE
Charts

### ISSUE THREAD

**Issue by AKprisonER** [vinniejames/coinfox#35]
Whats happened to cHArt and import functions

**Comment by AKprisonER** [comment]
I am using this portfolio

**Comment by vinniejames** [comment]
Charts should still be working. Which chart are you having trouble with?

I am reworking the import/export to be easier to use. I will update back here as soon as it's ready

**Comment by vinniejames** [comment]
Planning to use a URL based system instead https://github.com/vinniejames/coinfox/issues/15 please follow that issue

**Comment by vinniejames** [comment]
@AKprisonER I've added this functionality back in a nicer way with URL importing. Let me know if the charts are still giving you trouble and Im happy to investigate
