### ISSUE TITLE
Allow cost basis of 0

### ISSUE THREAD

**Issue by casey** [vinniejames/coinfox#8]
It would be nice to allow a cost basis of 0, in case one was gifted the coins, doesn't know the real cost basis, or one just doesn't want to keep track of cost basis.

PS: How am I the first star/issue on this? It's great!

**Comment by vinniejames** [comment]
Awesome, thanks @casey glad youre enjoying it.

This issue has been fixed https://github.com/vinniejames/coinfox/pull/12/commits/1b8a79402e8edbadd787bee8b61bcd6bed4f8c01

**Comment by vinniejames** [comment]
Also great to have now that many of us came upon free Bitcoin Cash. I had just been putting in `0.01` for the cost basis, but now you can do 0 as well

**Comment by vinniejames** [comment]
PS, not sure where you are using the app, but ive setup a new domain name for it here: [coinfox.co](http://coinfox.co)

Please update your bookmarks! Also if you "Add to Home Screen" on iOS or Android it works full screen just like a mobile app
